apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meetup-nginx
  name: meetup-nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meetup-nginx
  template:
    metadata:
      labels:
        app: meetup-nginx
    spec:
      containers:
      - image: registry.hub.docker.com/arunvarghe/nginx:latest
        imagePullPolicy: Always
        name: meetup-nginx
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: meetup-nginx-service
spec:
  selector:
    app: meetup-nginx
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
        
